-- Select Database
USE jsdb
GO
-- Create Table Comment Section
CREATE TABLE dbo.PRODUCTS
(PRD_ID int NOT NULL, PRD_DT DATE NOT NULL, PRD_FLAG VARCHAR(2) NOT NULL, CUST_DT DATE NOT NULL, CUST_FLAG VARCHAR(2) NOT NULL)
GO

--Add Column
ALTER TABLE dbo.PRODUCTS
ADD ITEM_ID INT NULL
GO

-- Insert Data
INSERT dbo.PRODUCTS (PRD_ID, PRD_DT, PRD_FLAG, CUST_DT, CUST_FLAG) VALUES ('110', '2015/03/10', 'AC', '2015/03/10', 'XY')
INSERT dbo.PRODUCTS (PRD_ID, PRD_DT, PRD_FLAG, CUST_DT, CUST_FLAG) VALUES ('111', '2015/04/10', 'AB', '2015/02/10', 'XZ')
INSERT dbo.PRODUCTS (PRD_ID, PRD_DT, PRD_FLAG, CUST_DT, CUST_FLAG) VALUES ('448', '2014/03/10', 'BC', '2015/03/10', 'MN')
INSERT dbo.PRODUCTS (PRD_ID, PRD_DT, PRD_FLAG, CUST_DT, CUST_FLAG) VALUES ('439', '2013/02/10', 'BD', '2016/03/10', 'XY')
INSERT dbo.PRODUCTS (PRD_ID, PRD_DT, PRD_FLAG, CUST_DT, CUST_FLAG) VALUES ('440', '2012/05/10', 'CA', '2018/03/10', 'NP')
GO

--Drop Primary Key Constraint - Developing
ALTER TABLE dbo.PRODUCTS
DROP CONSTRAINT PK_PRODUCTS_PRD_ID
GO

-- SELCT DATA
SELECT * FROM dbo.PRODUCTS
GO

--Sample Query
SELECT PRD_ID, PRD_DT
FROM dbo.PRODUCTS
GO

-- Answer Max Date and its corresponding flag
SELECT e1.PRD_ID, 
FROM PRODUCTS e1

